secrets:
  wireguard-config:
    file: ./wg0.conf

volumes:
  qbittorrent-home:

services:
  nginx-proxy:
    image: ${DOCKER_REGISTRY:-docker.io}/linkedmink/nginx-proxy
    build:
      context: ./nginx-proxy
      platforms:
        - "linux/amd64"
        - "linux/arm64"
    ports:
      - "80:80/tcp"
      - "443:443/tcp"
    develop:
      watch:
        - action: rebuild
          path: ./nginx-proxy/default.conf
          target: /etc/nginx/http.d/default.conf
  qbittorrent-wireguard:
    image: ${DOCKER_REGISTRY:-docker.io}/linkedmink/qbittorrent-wireguard
    build:
      context: ./qbittorrent-wireguard
      platforms:
        - "linux/amd64"
        - "linux/arm64"
    ports:
      - "8080:8080/tcp"
      - "51820:51820/udp"
    cap_add:
      - NET_ADMIN
    environment:
      INTERNAL_CIDRS: "172.16.0.0/12 192.168.0.0/16"
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
    volumes:
      - type: volume
        source: qbittorrent-home
        target: /home/torrent
      - type: tmpfs
        target: /var/log/torrent
        tmpfs:
          size: 1M
          mode: 0o01777
      - type: bind
        source: ./qbittorrent-wireguard/downloads
        target: /downloads
    secrets:
      - source: wireguard-config
        target: wg0.conf
  wireguard:
    image: ${DOCKER_REGISTRY:-docker.io}/linkedmink/wireguard
    command: /bin/sh
    build:
      context: ./wireguard
      platforms:
        - "linux/amd64"
        - "linux/arm64"
    ports:
      - "51820:51820/udp"
    cap_add:
      - NET_ADMIN
    environment:
      INTERNAL_CIDRS: "172.16.0.0/12 192.168.0.0/16"
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
    secrets:
      - source: wireguard-config
        target: wg0.conf
