services:
  nginx-proxy:
    image: ${DOCKER_REGISTRY:-docker.io}/linkedmink/nginx-proxy
    build:
      context: ./nginx-proxy
      platforms:
        - "linux/amd64"
        - "linux/arm64"
    ports:
      - "127.0.0.1:80:80/tcp"
      - "127.0.0.1:443:443/tcp"
    develop:
      watch:
        - action: rebuild
          path: ./nginx-proxy/default.conf
          target: /etc/nginx/http.d/default.conf
  qbittorrent-wireguard:
    image: ${DOCKER_REGISTRY:-docker.io}/linkedmink/qbittorrent-wireguard
    build:
      context: ./qbittorrent-wireguard
      platforms:
        - "linux/amd64"
        - "linux/arm64"
    ports:
      - "127.0.0.1:8080:8080/tcp"
